// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Places.Infrastructure.Persistence;

#nullable disable

namespace Places.Infrastructure.Migrations
{
    [DbContext(typeof(PlacesDbContext))]
    [Migration("20260425113229_PlaceUniqueIndexModification")]
    partial class PlaceUniqueIndexModification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("places")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Places.Domain.Entities.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExplorerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ValidationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Validation status of the check-in (Pending=0, Approved=1, Rejected=2)");

                    b.HasKey("Id");

                    b.HasIndex("ExplorerId")
                        .HasDatabaseName("IX_CheckIns_ExplorerId");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("IX_CheckIns_PlaceId");

                    b.HasIndex("ValidationStatus")
                        .HasDatabaseName("IX_CheckIns_ValidationStatus");

                    b.HasIndex("PlaceId", "ValidationStatus")
                        .HasDatabaseName("IX_CheckIns_PlaceId_ValidationStatus");

                    b.ToTable("CheckIns", "places");
                });

            modelBuilder.Entity("Places.Domain.Entities.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Detailed description of the place");

                    b.Property<int>("GeofenceRange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasComment("Radius in meters for geofence validation");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("double precision")
                        .HasComment("Geographic latitude coordinate");

                    b.Property<double>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("double precision")
                        .HasComment("Geographic longitude coordinate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PlaceCategoryId")
                        .HasColumnType("uuid");

                    b.Property<double>("TicketPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Places_CreatedAt");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Places_IsDeleted");

                    b.HasIndex("PlaceCategoryId")
                        .HasDatabaseName("IX_Places_PlaceCategoryId");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("IX_Places_Coordinates");

                    b.HasIndex("Name", "Latitude", "Longitude")
                        .IsUnique();

                    b.ToTable("Places", "places");
                });

            modelBuilder.Entity("Places.Domain.Entities.PlaceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Detailed description of the place category");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PlaceCategories_CreatedAt");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_PlaceCategories_IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_PlaceCategories_Name_Unique");

                    b.ToTable("PlaceCategories", "places");
                });

            modelBuilder.Entity("Places.Domain.Entities.PlacePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("URL of the place photo");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("IX_PlacePhotos_PlaceId");

                    b.HasIndex("Url")
                        .HasDatabaseName("IX_PlacePhotos_Url");

                    b.ToTable("PlacePhotos", "places");
                });

            modelBuilder.Entity("Places.Domain.Entities.PlaceReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CheckInId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Review comment/feedback from explorer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExplorerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether the review is verified by moderators");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Rating value (typically 1-5)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CheckInId");

                    b.HasIndex("ExplorerId")
                        .HasDatabaseName("IX_PlaceReviews_ExplorerId");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("IX_PlaceReviews_IsVerified");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("IX_PlaceReviews_PlaceId");

                    b.HasIndex("Rating")
                        .HasDatabaseName("IX_PlaceReviews_Rating");

                    b.HasIndex("PlaceId", "Rating")
                        .HasDatabaseName("IX_PlaceReviews_PlaceId_Rating");

                    b.ToTable("PlaceReviews", "places");
                });

            modelBuilder.Entity("Places.Domain.Entities.CheckIn", b =>
                {
                    b.HasOne("Places.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Places.Domain.Entities.Place", b =>
                {
                    b.HasOne("Places.Domain.Entities.PlaceCategory", "PlaceCategory")
                        .WithMany("Places")
                        .HasForeignKey("PlaceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Places.Domain.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("PlaceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Government")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("PlaceId");

                            b1.HasIndex("City");

                            b1.HasIndex("Government");

                            b1.ToTable("Places", "places");

                            b1.WithOwner()
                                .HasForeignKey("PlaceId");
                        });

                    b.Navigation("Address");

                    b.Navigation("PlaceCategory");
                });

            modelBuilder.Entity("Places.Domain.Entities.PlacePhoto", b =>
                {
                    b.HasOne("Places.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Places.Domain.Entities.PlaceReview", b =>
                {
                    b.HasOne("Places.Domain.Entities.CheckIn", "CheckIn")
                        .WithMany()
                        .HasForeignKey("CheckInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Places.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckIn");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Places.Domain.Entities.PlaceCategory", b =>
                {
                    b.Navigation("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
