apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rahal-api
  namespace: rahal
  labels:
    app.kubernetes.io/name: rahal-api
    app.kubernetes.io/component: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rahal.20.242.195.165.nip.io
      secretName: rahal-api-tls
  rules:
    - host: rahal.20.242.195.165.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rahal-api
                port:
                  number: 80
