DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'users') THEN
        CREATE SCHEMA users;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS users."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'users') THEN
        CREATE SCHEMA users;
    END IF;
END $EF$;

CREATE TABLE users."Admins" (
    "Id" uuid NOT NULL,
    "UserName" character varying(256) NOT NULL,
    "NormalizedUserName" text,
    "Email" character varying(256) NOT NULL,
    "NormalizedEmail" text,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" character varying(20) NOT NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "ProfilePictureURL" character varying(500) NOT NULL DEFAULT '',
    "Role" integer NOT NULL DEFAULT 1,
    "RefreshToken" character varying(500),
    "RefreshTokenExpiryTime" timestamp with time zone,
    CONSTRAINT "PK_Admins" PRIMARY KEY ("Id")
);

CREATE TABLE users."Explorers" (
    "Id" uuid NOT NULL,
    "Bio" character varying(500) NOT NULL DEFAULT '',
    "CountryCode" character varying(2) NOT NULL,
    "Gender" integer NOT NULL,
    "AvailableXp" integer NOT NULL DEFAULT 0,
    "CumaltiveXp" integer NOT NULL DEFAULT 0,
    "Level" integer NOT NULL DEFAULT 1,
    "IsPublic" boolean NOT NULL DEFAULT TRUE,
    "IsPremium" boolean NOT NULL DEFAULT FALSE,
    "PlanTierId" integer NOT NULL,
    "BirthDate" date NOT NULL,
    "UserName" character varying(256) NOT NULL,
    "NormalizedUserName" text,
    "Email" character varying(256) NOT NULL,
    "NormalizedEmail" text,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" character varying(20),
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "ProfilePictureURL" character varying(500) NOT NULL DEFAULT '',
    "Role" integer NOT NULL DEFAULT 0,
    "RefreshToken" text,
    "RefreshTokenExpiryTime" timestamp with time zone,
    CONSTRAINT "PK_Explorers" PRIMARY KEY ("Id")
);

CREATE TABLE users."VendorCategory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoryName" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_VendorCategory" PRIMARY KEY ("Id")
);

CREATE TABLE users."Vendors" (
    "Id" uuid NOT NULL,
    "CountryCode" character varying(2) NOT NULL,
    "Address" character varying(200) NOT NULL,
    "AddressUrl" character varying(500) NOT NULL,
    "WorkingHours" jsonb NOT NULL,
    "CategoryId" integer NOT NULL,
    "IsApproved" boolean NOT NULL DEFAULT FALSE,
    "UserName" character varying(256) NOT NULL,
    "NormalizedUserName" text,
    "Email" character varying(256) NOT NULL,
    "NormalizedEmail" text,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" character varying(20) NOT NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "ProfilePictureURL" character varying(500) NOT NULL DEFAULT '',
    "Role" integer NOT NULL DEFAULT 2,
    "RefreshToken" text,
    "RefreshTokenExpiryTime" timestamp with time zone,
    CONSTRAINT "PK_Vendors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Vendors_VendorCategory_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES users."VendorCategory" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_Admins_Email" ON users."Admins" ("Email");

CREATE UNIQUE INDEX "IX_Explorers_Email" ON users."Explorers" ("Email");

CREATE INDEX "IX_Vendors_CategoryId" ON users."Vendors" ("CategoryId");

CREATE UNIQUE INDEX "IX_Vendors_Email" ON users."Vendors" ("Email");

INSERT INTO users."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260316205504_UsersModuleInitial', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE users."Vendors" ALTER COLUMN "RefreshToken" TYPE character varying(500);

ALTER TABLE users."Explorers" ALTER COLUMN "Role" SET DEFAULT 2;

ALTER TABLE users."Explorers" ALTER COLUMN "RefreshToken" TYPE character varying(500);

UPDATE users."Explorers" SET "PhoneNumber" = '' WHERE "PhoneNumber" IS NULL;
ALTER TABLE users."Explorers" ALTER COLUMN "PhoneNumber" SET NOT NULL;
ALTER TABLE users."Explorers" ALTER COLUMN "PhoneNumber" SET DEFAULT '';

ALTER TABLE users."Admins" ALTER COLUMN "Role" SET DEFAULT 2;

INSERT INTO users."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260316220843_InitialCreate', '10.0.5');

COMMIT;

START TRANSACTION;
DROP TABLE users."Admins";

DROP TABLE users."Explorers";

DROP TABLE users."Vendors";

ALTER TABLE users."VendorCategory" DROP CONSTRAINT "PK_VendorCategory";

ALTER TABLE users."VendorCategory" RENAME TO "VendorCategories";

ALTER TABLE users."VendorCategories" ADD CONSTRAINT "PK_VendorCategories" PRIMARY KEY ("Id");

CREATE TABLE users."AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE users."AspNetUsers" (
    "Id" uuid NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "ProfilePictureURL" character varying(500) NOT NULL,
    "UserType" integer NOT NULL,
    "RefreshToken" character varying(500),
    "RefreshTokenExpiryTime" timestamp with time zone,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE users."AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES users."AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE users."AdminProfiles" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_AdminProfiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AdminProfiles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES users."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE users."AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES users."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE users."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES users."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE users."AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES users."AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES users."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE users."AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES users."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE users."ExplorerProfiles" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Gender" integer NOT NULL,
    "BirthDate" date NOT NULL,
    "Bio" character varying(500) NOT NULL,
    "CountryCode" character varying(2) NOT NULL,
    "AvailableXp" integer NOT NULL DEFAULT 0,
    "CumulativeXp" integer NOT NULL DEFAULT 0,
    "Level" integer NOT NULL DEFAULT 1,
    "IsPublic" boolean NOT NULL DEFAULT TRUE,
    "IsPremium" boolean NOT NULL DEFAULT FALSE,
    "PlanTierId" integer,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_ExplorerProfiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExplorerProfiles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES users."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE users."VendorProfiles" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "CountryCode" character varying(2) NOT NULL,
    "Address" character varying(200) NOT NULL,
    "AddressUrl" character varying(500) NOT NULL,
    "WorkingHours" jsonb NOT NULL,
    "CategoryId" integer NOT NULL,
    "IsApproved" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_VendorProfiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VendorProfiles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES users."AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_VendorProfiles_VendorCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES users."VendorCategories" ("Id") ON DELETE RESTRICT
);
COMMENT ON COLUMN users."VendorProfiles"."WorkingHours" IS 'JSON format: {"Monday": "09:00-17:00", ...}';

CREATE UNIQUE INDEX "IX_AdminProfiles_UserId" ON users."AdminProfiles" ("UserId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON users."AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON users."AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON users."AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON users."AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON users."AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON users."AspNetUsers" ("NormalizedEmail");

CREATE INDEX "IX_UserType" ON users."AspNetUsers" ("UserType");

CREATE UNIQUE INDEX "UserNameIndex" ON users."AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_ExplorerProfiles_IsDeleted" ON users."ExplorerProfiles" ("IsDeleted");

CREATE UNIQUE INDEX "IX_ExplorerProfiles_UserId" ON users."ExplorerProfiles" ("UserId");

CREATE INDEX "IX_VendorProfiles_CategoryId" ON users."VendorProfiles" ("CategoryId");

CREATE INDEX "IX_VendorProfiles_IsApproved" ON users."VendorProfiles" ("IsApproved");

CREATE INDEX "IX_VendorProfiles_IsDeleted" ON users."VendorProfiles" ("IsDeleted");

CREATE UNIQUE INDEX "IX_VendorProfiles_UserId" ON users."VendorProfiles" ("UserId");

INSERT INTO users."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260317114749_RefactorUserProfile', '10.0.5');

COMMIT;

START TRANSACTION;
INSERT INTO users."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260317120534_RoleConfig', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE users."AspNetUsers" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;

INSERT INTO users."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260324164655_UserSoftDeletion', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE users."AspNetUsers" ADD "PasswordResetOtp" text;

ALTER TABLE users."AspNetUsers" ADD "PasswordResetOtpExpiry" timestamp with time zone;

INSERT INTO users."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260401084531_ForgetPasswordOtp', '10.0.5');

COMMIT;

