apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  namespace: rahal
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: broker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi
